# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('file', models.FileField(upload_to='ads/', verbose_name='Файл')),
                ('duration', models.IntegerField(default=0, help_text='в секундах', verbose_name='Время показа')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
            },
        ),
        migrations.CreateModel(
            name='PlayListAdvertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('ads', models.ManyToManyField(to='advertising.Advertising', verbose_name='Рекламный список')),
            ],
            options={
                'verbose_name': 'Список рекламы',
                'verbose_name_plural': 'Список рекламы',
            },
        ),
    ]
