# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shop_and_sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('image', models.ImageField(upload_to='sales/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to=shop_and_sales.models.make_upload_path, verbose_name='Логотип')),
                ('photo', models.ImageField(upload_to=shop_and_sales.models.make_upload_path, verbose_name='Фото')),
                ('mapID', models.CharField(default='Позиция на карте', max_length=300)),
                ('mapLogo', models.ImageField(upload_to=shop_and_sales.models.make_upload_path, verbose_name='Логотип на карте')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop_and_sales.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
